### ISSUE TITLE
Wrong mobile provision profile

### ISSUE THREAD

**Issue by mr-const** [fastlane/gym#106]
I'm building project using jenkins with following flags:
```
gym build --verbose --configuration ${CONFIGURATION} --scheme MyProject \
--output_name ${FILENAME} \
--output_directory ${OUTDIR} \
-i "${CODE_SIGNING_IDENTITY}" \
-x "PROVISIONING_PROFILE=${PROVISIONING_PROFILE}" \
```
Before update to 0.72 version .ipa file was correctly provisioned with my PROVISION_PROFILE, after update gym to 0.72 (and 0.82) ipa contains invalid profile. I checked xcode archive - it contains correct mobile provision profile, so it seems to me, that gym overwrites provision profile after it was built and archived with xcodebuild.
How can I control this process and sign it with correct mobile provision?
```
00:10:15.885 [37mINFO [2015-09-24 16:09:04.34]: [0m[32mSuccessfully stored the archive. You can find it in the Xcode Organizer.[0m
00:10:15.885 [37mINFO [2015-09-24 16:09:04.35]: [0m[32mStored the archive in: [0m/var/lib/jenkins/Library/Developer/Xcode/Archives/2015-09-24/myProject-Release-2.1.1008 2015-09-24
```
This archive contains correct `embedded.mobileprovision`

```
00:10:56.466 [37mINFO [2015-09-24 16:09:45.33]: [0m[33mcd '/var/lib/jenkins/Library/Developer/Xcode/Archives/2015-09-24/myProject-Release-2.1.1008 2015-09-24 16.00.06.xcarchive/dSYMs' && zip -r '/var/lib/jenkins/workspace/MyProject-iOS/build/Release/myProject-Release-2.1.1008.app.dSYM.zip' 'MyProject.app.dSYM'[0m
00:11:00.351 [37mINFO [2015-09-24 16:09:49.22]: [0m  adding: MyProject.app.dSYM/ (stored 0%)
00:11:00.351   adding: MyProject.app.dSYM/Contents/ (stored 0%)
00:11:00.351   adding: MyProject.app.dSYM/Contents/Info.plist (deflated 53%)
00:11:00.351   adding: MyProject.app.dSYM/Contents/Resources/ (stored 0%)
00:11:00.351   adding: MyProject.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
00:11:00.351   adding: MyProject.app.dSYM/Contents/Resources/DWARF/MyProject (deflated 72%)
00:11:00.351 
00:11:00.351 
00:11:00.351 [37mINFO [2015-09-24 16:09:49.22]: [0m[32mSuccessfully exported and compressed dSYM file[0m
00:11:00.351 [37mINFO [2015-09-24 16:09:49.22]: [0m[32mSuccessfully exported and signed the ipa file:[0m
00:11:00.351 [37mINFO [2015-09-24 16:09:49.22]: [0m/var/lib/jenkins/workspace/MyProject-iOS/build/Release/myProject-Release-2.1.1008.ipa
```
This archive contains invalid `embedded.mobileprovision`

**Comment by KrauseFx** [comment]
It seems like your project is wrongly configured, please follow the [code signing guide](https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md) and make sure to set the correct provisioning profile via environment variables.

**Comment by mr-const** [comment]
Nope.
1. Project didn't change for months
2. gym was updated, xcode was updated.

And as I wrote - xcode embeds correct profile. Something happens later, when ipa zipped, or even later.

**Comment by KrauseFx** [comment]
You can always fallback to the old way of code signing: `gym(use_legacy_build_api: true)`, but it's not recommended. The new way of code signing does additional verifications of your code signing settings. 

Or use `gym --use_legacy_build_api true` from the command line.

**Comment by salabaha** [comment]
I have noticed similar problem. I was trying to build ad-hoc ipa but each time it include wrong provision profile. (It was signed with apple watch provision profile instead of main target provision profile). My target configuration include hardcoded code signing identity. But still I had the following config  
>
gym(clean: true, workspace: workspace, scheme: scheme, codesigning_identity: codesigning, export_method: 'ad-hoc', use_legacy_build_api: true)

Once I removed **codesigning_identity** from gym commend it began to works as expected and produce valid ipa file. 

So eventually working gym config for me is as follow. 
>
gym(clean: true, workspace: workspace, scheme: scheme, export_method: 'ad-hoc', use_legacy_build_api: true)

**Comment by salabaha** [comment]
Would be good if gym could validate generated ipa file against code signing errors. Would help a lot troubleshoot code signing problems.

**Comment by corristo** [comment]
I'm having exactly the same problem. What data could I provide?

**Comment by corristo** [comment]
It also looks like it somehow depends on the environment: I'm getting this issue when building Jenkins job, not everything seems correct on the same Mac when I'm running fastlane directly.

**Comment by corristo** [comment]
Manual call like this also produces incorrect ipa (archive is correct, though):
```/usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1449849908.plist' -archivePath '/path/to/archive' -exportPath '/tmp/1449849908'```

export options plist contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>method</key>
        <string>ad-hoc</string>
</dict>
</plist>
```

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1851. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
