### ISSUE TITLE
Gym cannot build schemes with scheme names containing a colon (:)

### ISSUE THREAD

**Issue by Evaugh** [fastlane/gym#124]
When the scheme you want Gym to build contains a colon (:) *or* any other scheme in the list of schemes in the XCode project or workspace contains a colon (e.g. a scheme named `TestFastLane: MySchemeName`), Gym fails with the error:

`Couldn't find specified scheme 'TestFastLane: MySchemeName'`

Running 

`xcrun xcodebuild -list -workspace './TestFastLane.xcworkspace'`

displays all the schemes, including `TestFastLane: MySchemeName`, correctly.

**Comment by KrauseFx** [comment]
This is caused because of this code

```
output = raw_info.split("Schemes:").last.split(":").first
```

Could you share the complete output when running

```
xcrun xcodebuild -list -workspace './TestFastLane.xcworkspace'
```

**Comment by Evaugh** [comment]
This lists the scheme as expected:

```
Information about workspace "TestFastLane":
    Schemes:
        TestFastLane
        TestFastLane: MySchemeName
```

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1848. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
