### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ericertl** [fastlane/gym#142]
Can you add a command like "ipa info" from "shenzhen" to show mobile provisioning information about an .ipa file?

**Comment by KrauseFx** [comment]
I can recommend using https://github.com/chockenberry/Provisioning to quickly see the profile of your app. Or do you want to use it from the command line?

**Comment by ericertl** [comment]
I use shenzhen from command line. It just would be nice to hace that functionality un gym, as shenzhen doesn't have much support lately.
It's only a suggestion to add.functionality for this gem.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1845. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
