### ISSUE TITLE
Support for WatchOS2 apps

### ISSUE THREAD

**Issue by mbjtrifork** [fastlane/gym#145]
Could really use that the watchkit_fix also supported WatchOS2

**Comment by mathiasAichinger** [comment]
@mbjtrifork I will work on it today. Will link the pull request to this issue.

**Comment by mathiasAichinger** [comment]
#148 should fix the issues

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1843. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
