### ISSUE TITLE
how can i debug?

### ISSUE THREAD

**Issue by pvinis** [fastlane/gym#146]
after building with gym, i get a .app. what extra steps do i have to do to be able to debug that will lldb?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1842. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
