### ISSUE TITLE
Build fails when watchkit .app is alphabetically before iOS .app

### ISSUE THREAD

**Issue by nicwise** [fastlane/gym#147]
I have a watchkit app called "myApp NZ Watch Kit App.app" and a normal app called "myApp NZ.app", and for some reason, the `generators/package_command_generator_legacy.rb` `appfile_path` method fails to find the right file - it find the WatchKit app.

(technically it doesn't FAIL, but it does .ipa the wrong .app)

I've fixed it in my version, but could there be a `--appname "MyApp NZ.app"` option or similar to make sure it finds the right one?

```
def appfile_path
        path = Dir.glob("#{BuildCommandGenerator.archive_path}/Products/Applications/myApp NZ.app").first

#this line - as it is in the prod version of gym - finds the wrong .app

        path ||= Dir.glob("#{BuildCommandGenerator.archive_path}/Products/Applications/*.app").first
        path ||= Dir[BuildCommandGenerator.archive_path + "/**/*.app"].last

        return path
      end
```

```
[buildserver@prodbuildserver Applications]$ ls -la
total 0
drwxr-xr-x   4 buildserver  staff   136 19 Nov 16:20 .
drwxr-xr-x   4 buildserver  staff   136 19 Nov 16:20 ..
drwxr-xr-x   3 buildserver  staff   102 19 Nov 16:20 myApp NZ WatchKit 1 App.app
drwxr-xr-x  95 buildserver  staff  3230 19 Nov 16:22 myApp NZ.app
[buildserver@prodbuildserver Applications]$ 
```

**Comment by benkane** [comment]
Should the two lines just be switched? If the .last fails (new way), fall back to the .first line (old way). I'm running into this same issue with my WatchKit app. The package command grabs the WatchKit app instead of my iOS app.

There really isn't any foolproof way to get the iOS app based on sorting. A better option would probably unfortunately be to add an optional paramater for the .app name. Although somewhere along the line I feel like Fastlane should already know the correct .app.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1841. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
