### ISSUE TITLE
Gym requires the UUID of the installed provisioning profile in order to locate it, but doesn't have a way of getting there from the app id 

### ISSUE THREAD

**Issue by johnlabarge** [fastlane/gym#151]
I would argue for a provisioning profile convention (which appears to be partially there) bundle_id_*enviornment* which is one of (dev|appstore|userdefined) and having the Gymfile have gym lookup the uuid from bundle_id and environment or something like that.  Gym isn't making my life any easier with this provisioning profile issue as it stands :/

**Comment by johnlabarge** [comment]
Right now I'm downloading the provisioning profiles to a local /profiles directory and doing this in my Gymfile
```ruby
    require "./uuid.rb"
    ENV['PROFILE_UDID'] = get_uuid("profiles/#     {ENV['BUILD']}_com.capitalonelabs.Flourish.mobileprovision") 
```
where `$BUILD` is assumed to exist and get_uuid is this unfortunate mess: 

```ruby 
def get_uuid(path)
    `security cms -D -i #{path} >/tmp/profile.plist; PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /tmp/profile.plist); rm /tmp/profile.plist; echo $PROFILE_UUID`.chop
end
```

I *think* there must be something that I'm missing, but haven't found it yet

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1840. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
