### ISSUE TITLE
dsym is not getting zipped

### ISSUE THREAD

**Issue by arunks** [fastlane/gym#154]
I am building my app right now with - 
include_symbols: "true",

At the end of the process I expect the dsym to be zipped for easy upload to distribution mechanisms. But I dont see the ZIP file. Has this feature been removed? Or do I have to write a postscript?

**Comment by taehoon-jung** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
정태훈(JUNG TAEHOON)(ios@worksmobile.com) 님은 현재 부재중입니다.</br>
보내신 메일 <[gym] dsym is not getting zipped (#154)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
정태훈(JUNG TAEHOON)(ios@worksmobile.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-12-04 00:00 ~ 2015-12-04 23:59 GMT +09:00]<br>개인 사유로 연차를 사용합니다. 
--------------------------------------------

**Comment by KrauseFx** [comment]
It should be zipped. Taking a look at this now :+1:

**Comment by KrauseFx** [comment]
Running `gym` generated a `dSYM` file for me, it seems to be working. Could you provide more information and ideally an example app that runs into this problem?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1839. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
