### ISSUE TITLE
Gym Crashing Trying to Export Archive

### ISSUE THREAD

**Issue by justin** [fastlane/gym#162]
Trying to test out Fastlane tools with a new project, but getting a crash when it tries to export my archive.

I submitted this as a crash report. Crash id is "ffe0dbcd069a055f2055958c694444df"

This is from my `Gymfile`. 

```
workspace "Project.xcworkspace"
scheme "Project"
sdk "iphoneos9.2"
configuration "Release"
output_directory "./build"
codesigning_identity "iPhone Distribution: Client Name Inc"
```

let me know what else i can provide you to get this figured out.

**Comment by KrauseFx** [comment]
Can you share the complete log output when running `gym`?

**Comment by justin** [comment]
Sure: https://gist.github.com/justin/2b3e10167197b8f9e028

**Comment by KrauseFx** [comment]
That's a weird error that's caused by this `xcodebuild` command 
```
/usr/bin/xcrun xcodebuild -exportArchive -exportOptionsPlist '/tmp/gym_config_1450118225.plist' -archivePath '/Users/justin/Library/Developer/Xcode/Archives/2015-12-14/EventLink 2015-12-14 11.36.48.xcarchive' -exportPath '/tmp/1450118225' 
```

You could try updating your `Gymfile` to also have `use_legacy_build_api true`, as this will use the Xcode 6 API to sign your app.

**Comment by justin** [comment]
That doesn't seem to help. I swapped to that and this is the new gist: https://gist.github.com/justin/2b3e10167197b8f9e028

**Comment by yoneapp** [comment]
I also had a problem similar. Problem has been resolved.

$ bundle exec fastlane xxx -> $ fastlane xxx

Just for information.

**Comment by lacostej** [comment]
I've added 2 PR that might help fix or troubleshoot this further. See #176 and #178.

**Comment by KrauseFx** [comment]
Bundling a new release now :+1:

**Comment by KrauseFx** [comment]
:rocket:

**Comment by rammangai87** [comment]
The reason is the method parameter in the exportOptions.plist should exactly match the type of provisioning profile which is used to codesign the Archive.

Ex: If it is an enterprise profile - then the value of method should be enterprise. The Same applies for app-store as well.

A quick note - If our application has swift files in it - the exportarchive produces SwiftSupport folder only in case of app-store method in exportOptions.plist. If you provide enterprise, it wont include the folder in the resulting ipa.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1835. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
