### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by radex** [fastlane/gym#167]
I think it would be great if I could use Gym on my build server for automated Mac builds. (I'm currently using raw xcodebuild and it's fine, but produces broken release builds without setting up proper archiving)

I might be potentially interested in doing the work to support it if the directorate approves ;)

**Comment by KrauseFx** [comment]
`gym` already does support Mac apps. Or did you run into problems using it?

**Comment by KrauseFx** [comment]
There is even a Mac project example in the `examples` directory

**Comment by SemenovAlexander** [comment]
As far, as Deliver started to support upload .pkg files, we've also decided to upload new builds to appstore using fastlane. 

The issue is gym doesn't generate any `.pkg` archive to be able pass forward to Deliver. 

I've tried to user `xcexport` action, but it produces pkg with invalid provisioning profile...

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1833. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
