### ISSUE TITLE
Missing Beta Entitlement on upload to ITC

### ISSUE THREAD

**Issue by thekeshavgoel** [fastlane/gym#173]
I'm using gym (v1.2.0) and I tried using the Adhoc as well as Distribution(App Store) provisioning profiles. But every time I got the same error uploading it to ITC (Using Application Loader). 
"WARNING ITMS-90191: "Missing beta entitlement. Your app does not include the beta-reports-active entitlement. If you intend to distribute this build via TestFlight for beta testing, please re-build this app with a newly generated provisioning profile."

The command I'm using for Build is:

gym build --workspace "App.xcworkspace" --scheme "AppScheme" --codesigning_identity "iPhone Distribution: XYZ(RTS..)" --buildlog_path "$path" --output_directory "$path/build/" --output_name "App.ipa" --clean --verbose --use_legacy_build_api true --export_method app-store

Note: (Xcode version is 7.2, So used "--use_legacy_build_api true")
Please tell me if I'm doing something wrong? Or should I try some other options.

**Comment by SemenovAlexander** [comment]
also have related issue. 
But our case is pretty strange - app uploads without problem, and iTunes Connect shows no issues, but app can't be installed through TestFlight app. 
Error is "The app couldn't be installed because it is missing the beta entitlement".

While uploading build through XCode - all works without problems.

It is, probably, some issue with provisioning profiles, but I've regenerated them couple times, and all worked fine about a month ago with same versions of XCode and Pilot.

**Comment by Econa77** [comment]
same here.

**Comment by thekeshavgoel** [comment]
@SemenovAlexander & @Econa77 : Try using option --export_method [ad-hoc/app-store]
(ad-hoc for local use/share. app-store if you wish to use the app through Test-flight and use App store Distribution provisioning profiles).

**Comment by SemenovAlexander** [comment]
@thekeshavgoel thanks for that advise, but it didn't work for me (btw, gym sets export_method to "app-store" by default).

Finally, I've tried to remove `use_legacy_build_api` flag and all works fine now

**Comment by Econa77** [comment]
@thekeshavgoel @SemenovAlexander thanks!

It was successful result I also removed the `use_legacy_build_api`.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1831. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
