### ISSUE TITLE
Ability to add manifest to exportOptionsPlist for enterprise deployment

### ISSUE THREAD

**Issue by iONsky** [fastlane/gym#180]
At the moment I have to create an extra manifest plist file for my enterprise app deployment by hand. Since Xcode 7 it will be generated automatically when you add a 'manifest' dictionary into the exportOptionsPlist.

Sadly I haven't found a way to tell gym to add this to the exportOptionsPlist when exporting an ipa.

Do you think it would be possibly to have a parameter to pass the content of the manifest dictionary?

Here is the output from `xcodebuild -help` about the manifest I'm talking about:

> manifest : Dictionary
> For non-App Store exports, users can download your app over the web by opening your distribution manifest file in a web browser. To generate a distribution manifest, the value of this key should be a dictionary with three sub-keys: appURL, displayImageURL, fullSizeImageURL. The additional sub-key assetPackManifestURL is required when using on demand resources.

**Comment by KrauseFx** [comment]
That's a great feature request, I like it :+1:

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1830. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
