### ISSUE TITLE
Multiple schemes with Gymfile

### ISSUE THREAD

**Issue by pranavss11** [fastlane/gym#186]
I have a project that has multiple schemes/targets. Is there a way to setup Gym to build multiple schemes through a gym file?

**Comment by KrauseFx** [comment]
Yeah, you should use [fastlane](https://github.com/fastlane/fastlane) for that. You might also want to check out https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md#multiple-targets-of-the-same-underlying-app

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1829. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
