### ISSUE TITLE
Expose new Swift toolchain flag for Xcode 7.3

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/gym#187]
Re-duplication of https://github.com/fastlane/fastlane/issues/1079

In the new `xcodebuild` we will be able to specify which version of swift we wish to use. This is just a note to add support for it, once Xcode 7.3 is released.

We should add an extra flag for `gym` which will pass the toolchain of swift to use, (Unless Gym just accepts the same flags that xcodebuild does).

We should expose this new flag to the `gym` action inside of fastlane.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1828. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
