### ISSUE TITLE
silent mode: to be more silent

### ISSUE THREAD

**Issue by fvisticot** [fastlane/gym#211]
To much lines displayed even with silent = true
- Compiling
- Copying

would be nice to see only compilation warning / error

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1823. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
