### ISSUE TITLE
[feature request] change title field in manifest.plist after changing app's display name

### ISSUE THREAD

**Issue by plrthink** [fastlane/gym#214]
I'm using gym's export_options with fastlane update_info_plist action. But changing app display name doesn't affect title filed in generated manifest.plist file, the title's value still stays unchanged. Below are related lines in my Fastfile

````ruby
update_info_plist(
  display_name: "new name",
  plist_path: plist_path
)

...

gym(
  export_options: {
    method: "ad-hoc",
    manifest: {
      appURL: "",
      displayImageURL: "",
      fullSizeImageURL: ""
    }
  }
)
````

And here is generated `manifest.plist`'s related things:

````
<key>metadata</key>
<dict>
  <key>bundle-version</key>
  <string>1.0</string>
  <key>kind</key> 
  <string>software</string>
  <key>title</key>
  <string>old name</string>
</dict>
````

As you can see, the title field stays unchanged. Of course I can manually or write a script to change it but I think it makes sense that gym do this work.

Any ideas?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1821. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
