### ISSUE TITLE
use_legacy_build_api always true

### ISSUE THREAD

**Issue by yzlhccdec** [fastlane/gym#217]
I'm using circleci for daily build, I can't set use_legacy_build_api to false when building, It's just not working.
I've tried
gym -s "$BUILD_SCHEME" -n "XXX.$GIT_COUNT" -j "ad-hoc" -o "build" -c --use_legacy_build_api false
gym -s "$BUILD_SCHEME" -n "XXX.$GIT_COUNT" -j "ad-hoc" -o "build" -c

the version of Xcode for building is 7.2，I always get the message "Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816"

Please help! Thank you

**Comment by yzlhccdec** [comment]
+----------------------+--------------------------+
|              Summary for gym 1.6.1              |
+----------------------+--------------------------+
| workspace            | ./CalorieCal.xcworkspace |
| scheme               | iCalorie Dev             |
| clean                | true                     |
| output_directory     | build                    |
| output_name          | iCalorie.49714c1         |
| silent               | false                    |
| use_legacy_build_api | true                     |
| export_method        | ad-hoc                   |
| buildlog_path        | ~/Library/Logs/gym       |
| destination          | generic/platform=iOS     |
+----------------------+--------------------------+

**Comment by wxytjustb** [comment]
if you use --use_legacy_build_api, it shows the use_legacy_build_api is true

**Comment by mfurtak** [comment]
Hi @yzlhccdec - thanks for the report! :+1: 

@wxytjustb is right. Because `--use_legacy_build_api` is a boolean switch, just including it on the command line makes the value true. On the command line, specifying `true` or `false` after it has no effect.

Can you check on a couple things?

1. Can you check to see if you have a `Gymfile` somewhere in your project which is specifying `use_legacy_build_api true`
1. Can you make sure that the Xcode installation pointed to by `xcode-select -p` is indeed the Xcode 7.2 installation you want to be using

Thanks!

**Comment by yzlhccdec** [comment]
hi @mfurtak , thanks for your reply.
I tried "gym -s "$BUILD_SCHEME" -n "XXX.$GIT_COUNT" -j "ad-hoc" -o "build" -c", but it doesn't work either.
I don't have any Gymfile in my project, and the command "Xcode-select -p" shows "/Applications/Xcode-7.3.app/Contents/Developer"

**Comment by lacostej** [comment]
@yzlhccdec what does

`ruby -e 'require "fastlane"; puts FastlaneCore::Helper.xcode_version '` outputs ?

**Comment by yzlhccdec** [comment]
./scripts/build.sh
iCalorie Dev
01742c0
7.3（<-this is the output of the ruby command）
[18:02:00]: xcrun xcodebuild -list -workspace './CalorieCal.xcworkspace'
2016-02-23 18:02:01.162 xcodebuild[965:6397] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
[18:02:09]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816

+----------------------+--------------------------+
|              Summary for gym 1.6.1              |
+----------------------+--------------------------+
| workspace            | ./CalorieCal.xcworkspace |
| scheme               | iCalorie Dev             |
| clean                | true                     |
| output_directory     | build                    |
| output_name          | iCalorie.01742c0         |
| silent               | false                    |
| use_legacy_build_api | true                     |
| export_method        | ad-hoc                   |
| buildlog_path        | ~/Library/Logs/gym       |
| destination          | generic/platform=iOS     |
+----------------------+--------------------------+

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1820. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
