### ISSUE TITLE
Add the ability to remove xcarchive file on completion of ipa export

### ISSUE THREAD

**Issue by RobDay** [fastlane/gym#228]
It would be pretty cool if Gym had the ability to clean up xcarchives after the ipa is generated.  This should definitely not be a default behavior, but it would be a useful feature when considering CI. Our CI server kicks off a large amount of builds and it's currently a manual task to clean up all archives we want deleted (we keep our app store flavors but purge our CI flavors).  

Does removing xcarchives sound valuable? Is it something that should live in Gym or perhaps as a build action?

**Comment by KrauseFx** [comment]
This should be its own fastlane action, however I don't see the big value in deleting those folders. Those archives are usually useful to get the symbolication files or just check them after submitting the app to the App Store.

**Comment by RobDay** [comment]
They definitely shouldn't be deleted by default, but we wouldn't want to hold onto every build that ever gets kicked off through CI.  Our IPAs get sent off to an internal downloading site where users can download and test out builds.  At that point, we never need the archive for builds that aren't intended for the app store.

If this isn't something you think others would be interested in, I'll implement as a custom action.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1818. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
