### ISSUE TITLE
[Feature]Add a parameter reporter 

### ISSUE THREAD

**Issue by ebaujard** [fastlane/gym#229]
With a parameter  "reporter" we could generate a json-compilation-database, and use this file with action oclint.

Ex in build_command_generator.rb:
 pipe << "| tee #{xcodebuild_log_path.shellescape} | xcpretty --report  #{reporter}"

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1817. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
