### ISSUE TITLE
Show provisioning profile and cert used

### ISSUE THREAD

**Issue by Reedyuk** [fastlane/gym#70]
A nice to have, when you use the Xcode build command then it outputs the cert and provisioning profile.
Could you make it so that gym does this, as when I view the build logs, I can see historically what was used.

**Comment by KrauseFx** [comment]
You mean this should be displayed right before building the application in the table summary? I like the idea :+1:

**Comment by KrauseFx** [comment]
This could even be part of all the other tools. What do you think?

**Comment by Reedyuk** [comment]
Yeah I think so, most of my broken builds are usually down to provisioning profile errors, so it's handy to know what is being used.

**Comment by KrauseFx** [comment]
I like the idea, thanks @Reedyuk :+1:

**Comment by superarts** [comment]
Here `gym` keeps using the wildcard provisioning profile which breaks push notification and other things. It would be helpful to have it shown, maybe along with `xcrun xcodebuild -showBuildSettings -workspace './whitelabel.xcworkspace' -scheme 'Template'`... Or indicate where "Installing provisioning profile..." come from.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1865. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
