### ISSUE TITLE
Custom output_name variables

### ISSUE THREAD

**Issue by mmajewski** [fastlane/gym#71]
It would be nice if I could add to output_name number of build. In my script from build phases it was getting by line buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$INFOPLIST_FILE")

Then, in gymfile:
output_name "MyApp_v{build}"
or something like that.

What do yout think about this?

**Comment by Reedyuk** [comment]
I think it should take the bundle version and build number and append that to the table that gets drawn when building.
There is a table that mentions the appname.app in the output so maybe it would be appname.app bundle version build number.

**Comment by johncblandii** [comment]
+1 for this one. We append dates to ours as well. Build number would be another solid add though.

**Comment by pranavss11** [comment]
+1 for this. Does anyone know if there's a work around for this for now?

**Comment by KrauseFx** [comment]
If you use `fastlane` this is really easy to add, as you can rename the file after building.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1864. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
