### ISSUE TITLE
Gym not using bundle identifier automatically?

### ISSUE THREAD

**Issue by vCrespoP** [fastlane/gym#74]
Hi again dear Krause,

I have this code like this:
```ruby
...
ENV["PROFILE_UDID"] = {Return_value_of_sigh}
...
    ipa({
      workspace: "NAME.xcworkspace",
      configuration: "Release",
      scheme: "NAME",
      clean: true
    })


This is the code I'd like to use:
   gym(
       workspace: "NAME.xcworkspace",
       scheme: "NAME",
       configuration: "Release",
       clean: true,
       silent: true
    )
```

But gym asks me to select a provisioning profile, which makes the automated process break if I don't always use "sigh" first and export that to env varaible (which I don't know if it will ever happen, but just in case).

Could this be automatically done by obtaining the bundle identifier in some way if not? This would make lanes even more independent.

Thanks again!!

**Comment by KrauseFx** [comment]
Sure thing, check out the code signing guide: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md

Basically you can set the provisioning profile statically in your project file to not have to specify it when using `gym`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1862. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
