### ISSUE TITLE
Changing Scheme Name

### ISSUE THREAD

**Issue by ovuncmetin** [fastlane/gym#84]
Hi,

Can I change the schema name with gym or add PRODUCT_NAME that i can use with xcodebuild?

Thanks.

**Comment by KrauseFx** [comment]
You mean similarly to https://github.com/fastlane/gym/issues/60? 

If so, you can use those newly added `fastlane` actions: https://github.com/KrauseFx/fastlane/pull/531/files

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1858. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
