### ISSUE TITLE
Improve the output for non-fatal crashes

### ISSUE THREAD

**Issue by mattyohe** [fastlane/gym#96]
`gym 0.7.2`

This might be a part of a larger cleanup of error handling and display, but simply running gym in a folder without a project present shouldn't crash.

**Comment by KrauseFx** [comment]
It raises an exception because there was no project to be found. You get the success return code when everything was successful and you generated an `ipa` file (which you didn't if there is no project)

Let's imagine you have `gym` as one of the steps in your `Fastfile` you'd expect to have an `ipa` file for the following steps if it didn't fail.

Does this make sense?

**Comment by mattyohe** [comment]
> Let's imagine you have gym as one of the steps in your Fastfile you'd expect to have an ipa file for the following steps if it didn't fail.

Sure, but I don't expect running `gym` in the wrong directory will spit out a stack trace. Returning the error code of 1 or similar (which the current behavior does) is perfectly acceptable but not the trace.

All I'm recommending is better/meaningful output to the user. Take for example running `pod install` in a directory without a Podfile. You get nice output via `CLAide::InformativeError`. See [this](https://github.com/CocoaPods/CocoaPods/blob/34156c097996e26b75d0f8ae002fb0a6b4d6b636/lib/cocoapods/command.rb#L124).

Believe me, I know there's a lot to work on on this project ahead, and I appreciate your work, but I'm only bringing this up because this error was my first experience and introduction to `gym` today.

**Comment by KrauseFx** [comment]
Thank you so much for your feedback @mattyohe, I didn't want to come of as rude for immediately closing this issue.

I agree, there is room for improvement - right now all fastlane tools will just `raise` when there is *any* error that causes the tool to not finish its job.

I'll leave this issue open to work on an improved exit system :+1: Thanks again for your feedback.

**Comment by lacostej** [comment]
I meant #94 not #96 in my above link

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1853. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
